/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DBUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author DELL
 */
public class P_thongke extends javax.swing.JPanel {

    /**
     * Creates new form P_thongke
     */
    public P_thongke() {
        initComponents();
    }
    
    public JPanel datase() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            for (int i = 1; i < 13; i++) {
                String sql = "Select sum(soluong*giaban)\n"
                        + "from DonHangChiTiet inner join SanPham on DonHangChiTiet.Masp=SanPham.Masp\n"
                        + "					inner join Donhang on DonHangChiTiet.MaDH=Donhang.MaDh\n"
                        + "where YEAR(Ngaymua)=" + Integer.parseInt(txt_nam.getText()) + "and MONTH(Ngaymua)=" + i;
                Connection conn = DBUtils.getConnection();
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                double a = 0;
                while (rs.next()) {
                    a = rs.getDouble(1);
                }
                dataset.setValue(a, "Doanh thu", "" + i);

            }
        } catch (Exception e) {
        }
        String title = "Biểu đồ doanh thu 12 tháng trong năm " + txt_nam.getText();
        JFreeChart chart = ChartFactory.createLineChart(title, "Tháng", "VNĐ", dataset);
        ChartPanel panel = new ChartPanel(chart);
        return panel;
    }

    public JPanel datase1() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            for (int i = 1; i < 13; i++) {
                String sql = "Select sum(soluong*(giaban-gianhap))\n"
                        + "from DonHangChiTiet inner join SanPham on DonHangChiTiet.Masp=SanPham.Masp\n"
                        + "					inner join Donhang on DonHangChiTiet.MaDH=Donhang.MaDh\n"
                        + "where YEAR(Ngaymua)=" + Integer.parseInt(txt_nam.getText()) + "and MONTH(Ngaymua)=" + i;
                Connection conn = DBUtils.getConnection();
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                double a = 0;
                while (rs.next()) {
                    a = rs.getDouble(1);
                }
                dataset.setValue(a, "Lợi nhuận", "" + i);

            }
        } catch (Exception e) {
        }
        String title = "Biểu đồ lợi nhuận 12 tháng trong năm " + txt_nam.getText();
        JFreeChart chart = ChartFactory.createLineChart(title, "Tháng", "VNĐ", dataset);
        ChartPanel panel = new ChartPanel(chart);
        return panel;
    }

    public boolean txt() {
        if (txt_nam.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống năm");
            return false;
        }
        if (!txt_nam.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Năm phải nhập là giá trị số");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_loai = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        panel_bieudo = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 204));
        setMaximumSize(new java.awt.Dimension(915, 540));
        setMinimumSize(new java.awt.Dimension(915, 540));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(915, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(915, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(915, 35));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THỐNG KÊ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel2.setText("Năm:");

        jLabel3.setText("Biểu đồ:");

        cb_loai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doanh thu", "Lợi nhuận" }));

        jButton1.setText("Hiện biểu đồ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_bieudoLayout = new javax.swing.GroupLayout(panel_bieudo);
        panel_bieudo.setLayout(panel_bieudoLayout);
        panel_bieudoLayout.setHorizontalGroup(
            panel_bieudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        panel_bieudoLayout.setVerticalGroup(
            panel_bieudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cb_loai, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_bieudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cb_loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(panel_bieudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txt()) {

            if (cb_loai.getSelectedItem().equals("Doanh thu")) {
                panel_bieudo.removeAll();
                JPanel panel = datase();
                panel.setSize(panel_bieudo.getSize());
                panel_bieudo.add(panel);
                panel_bieudo.repaint();
            } else {
                panel_bieudo.removeAll();
                JPanel panel = datase1();
                panel.setSize(panel_bieudo.getSize());
                panel_bieudo.add(panel);
                panel_bieudo.repaint();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_loai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_bieudo;
    private javax.swing.JTextField txt_nam;
    // End of variables declaration//GEN-END:variables
}
